### ISSUE TITLE
Funtions not available after script save

### ISSUE THREAD

**Issue by GetBroccoli** [fuzzysteve/eve-googledocs-script#12]
I created a new script in the script editor and copied the EveCentralPrices.gs script, however google docs doesn't autocomplete the function loadXPrices or return values for them when they are entered. I get an error telling me the reference does not exist. You can see the doc I'm trying to use it in here:
https://docs.google.com/spreadsheets/d/1-i6Sy9JHtZtKPEkGd1mjb9xHkKhykRHXL5UkHcPZvx8/edit?usp=sharing

Shots in the dark:
Running script in editor returns error 'need typeids' from line 46 or 111.

adding;
var priceIDs =34;

to start of function in hopes of debugging it returns same error. No idea what I'm going in Java though.

**Comment by GetBroccoli** [comment]
EDIT:
I narrowed my reference from B:B to B3 and the error changed to a missing function error. So yea, function just isn't showing up :/

**Comment by ghostwolf74** [comment]
I'm having a similar issue where I'm trying to use EveCentralPrices.gs and getting an error: "TypeError: Cannot find function forEach in object #REF!. (line38)"  

Doesn't matter how small the request is.

**Comment by jjcalvo** [comment]
Get the same forEach error.

**Comment by rsoldatenko** [comment]
In script example:
loadSystemPrices(A1:A28) - function must get range as input parameter

if use loadSystemPrices(A1) - TypeError: Cannot find function forEach in object xxxxx.
if use   loadSystemPrices(A1:A2) - all work.
