### ISSUE TITLE
loadSystemPrices not loading properly due to getChildren error

### ISSUE THREAD

**Issue by ErsinL** [fuzzysteve/eve-googledocs-script#15]
Hi Fuzzy,

I have been using your EveCentralPrices script for a while now, specifically the loadSystemPrices function, and it has been working flawlessly except for the last few days.  When trying to load the function, I get TypeError: cannot call method "getChildren" of null.  I have pasted below a link to part of my google spreadsheet.
https://docs.google.com/spreadsheets/d/11FVbKo-kRiFaCBdAQs4TnfBZwxz9HaxkWVUcCK3kzf4/edit?usp=sharing
If you could help me resolve this I'd greatly appreciate it.

**Comment by fuzzysteve** [comment]
Eve central is acting up right now. https://eve-central.com/

You _could_ shift over to using https://market.fuzzwork.co.uk/api/
