### ISSUE TITLE
CHARACTERID, can´t find it

### ISSUE THREAD

**Issue by Mezoti** [fuzzysteve/eve-googledocs-script#16]
Hi 

I have been trying to get your esiwalletpull to work, but i am having trouble With getting the CHARACTERID, i have try to use the following lookup =IMPORTDATA("https://esi.tech.ccp.is/latest/search/?search=J%J&categories=character&language=en-us&strict=true&datasource=tranquility"), and i get some weard Numbers that is NOT working in the script, i get a error saying that the id do NOT match the token.
Do you have an idea to what i am doing wrong, or am i getting the characterid the wrong Way.

**Comment by Mezoti** [comment]
problem solved.

**Comment by fuzzysteve** [comment]
Gah! I meant to respond on this. Sorry 😯



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
