### ISSUE TITLE
I think the API may be broken

### ISSUE THREAD

**Issue by ryanniccolls** [fuzzysteve/eve-googledocs-script#22]
Error
Request failed for https://api.eveonline.com/char/Blueprints.xml.aspx?keyID=6810907&vCode=BU1DTvQsVtzzcJtKkkuBZwCd0DXVGmNcIJqvf4EV6gF0HVPUmdNi3J493h9hbbJl&characterID=2113381903 returned code 403. Truncated server response: <?xml version='1.0' encoding='UTF-8'?> <eveapi version="2"> <currentTime>2018-03-17 23:05:28</currentTime> <error code="221">Illegal page re... (use muteHttpExceptions option to examine full response). (line 22).

**Comment by fuzzysteve** [comment]
I can't help with that, I'm afraid. That's CCP's side.
