### ISSUE TITLE
Too many calls for fetchApp

### ISSUE THREAD

**Issue by FooDownunder** [fuzzysteve/eve-googledocs-script#5]
I now need to cache.

function cacheUrlFetchApp(fetchUrl, parameters){
  
  // Set up public cache
  var cache = CacheService.getScriptCache();
  // Turn the requested URL into a string based on the MD5.  
  var digest = Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.MD5, fetchUrl));
  
  // Based on this MD5, lookup the URL in the cache
  var cached = cache.get(digest);
  
  // If a result has been already cached, use it
  if (cached  != null) {
    return cached;
  }

  // Fetch the url
  var resultXML = UrlFetchApp.fetch(fetchUrl,parameters);
  // Don't call too quickly, google gets sad.  Still pushing it a little
  Utilities.sleep(100); 
  // Get the text of the URL call
  var result =resultXML.getContentText();
  // Cache the result
  cache.put(digest,result,21600) //maximum cache time is 6 hours, or 21600 seconds.
  
  // return the result
  return result;
  
}

in the load system prices, instead of calling var xmlFeed = UrlFetchApp.fetch(url + temparray.join("&typeid="), parameters).getContentText();
I now call var xmlFeed = cacheUrlFetchApp(url + temparray.join("&typeid="), parameters);

**Comment by mrjackk123** [comment]
Is this supposed to fix this ? 

"Error
Service invoked too many times for one day: urlfetch. (line 66)."

Line 66 : 
var xmlFeed = UrlFetchApp.fetch(url+temparray.join("&typeid="), parameters).getContentText();

I tried your function Foo, but is there anything more than adding this code + editing the loadSystemPrices ? How is it supposed to work ? Why do I have this "Service invoked too many times for one day" even though I'm not using the document for the entire day ??

Thanks

**Comment by FooDownunder** [comment]
The service invoked too many times issue can be minimised by caching.  I am
*still* not happy with my current solution.

I now use a cache for
https://docs.google.com/spreadsheets/d/1lXM8PqU0Tn4EJJ2xRuI7uo55IrZ7MKWJidK9T_bA9L4/edit#gid=0


This is better, but still not great.  With my published documents, I still
hit limits.  With my private use documents, it is OK

function cacheUrlFetchApp(fetchUrl, parameters){

  // Set up public cache
  var cache = CacheService.getScriptCache();
  // Turn the requested URL into a string based on the MD5.
  var digest =
Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.MD5,
fetchUrl));

  // Based on this MD5, lookup the URL in the cache
  var cached = cache.get(digest);

  // If a result has been already cached, use it
  if (cached  != null) {
    return cached;
  }


  // Don't call too quickly, google gets sad.  I want the different calls
to start at different times
  Utilities.sleep(Math.random() * 5000);;

  // Fetch the url
  var resultXML = UrlFetchApp.fetch(fetchUrl,parameters);

  // Get the text of the URL call
  var result =resultXML.getContentText();
  // Cache the result
  cache.put(digest,result,21600) //maximum cache time is 6 hours, or 21600
seconds.

  // return the result
  return result;
  }
