### ISSUE TITLE
Problem with update prices

### ISSUE THREAD

**Issue by iLifeHack** [fuzzysteve/eve-googledocs-script#8]
In google-docs i insert market prices script and do trigger on 5 min, also 3 param is 1 in function but prices don`t update((

**Comment by clonerworks** [comment]
@iLifeHack Do you have an example you could link here with edit access to anyone with the link so we can look at it and possibly fix it up?

**Comment by iLifeHack** [comment]
Sorry but update is working but it very long period, i fink maybe better use CREST scripts its live update can be

**Comment by clonerworks** [comment]
are you using the cache breaker?

**Comment by iLifeHack** [comment]
no

**Comment by clonerworks** [comment]
The reason the cache buster variable is there is because it will force a refresh on the data.
If you dont use it google can cache the data also and it wont auto refresh when the sheet is opened.
Try using it and see how you go.

**Comment by iLifeHack** [comment]
last variable =1 but prices don`t updating and with CREST script last var =1 but prices don`t updating maybe wrong var?

**Comment by iLifeHack** [comment]
maybe disable triggers in scripts?
